### ISSUE TITLE
mod.communicator.PODocsError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by l80** [VorskiImagineering/C3PO#1]
My *.po files there are in the '/Volumes/svnnew/agesage_/main/locale/nma/'. After start C3PO script with synchronize command script stop with exception:

```
$ python c3po_cmd.py synchronize -l /Volumes/svnnew/agesage_/main/locale/nma/
Traceback (most recent call last):
  File "c3po_cmd.py", line 23, in <module>
    main()
  File "c3po_cmd.py", line 19, in main
    getattr(com, command[0])()
  File "/Volumes/svnnew/c3p0/C3PO/c3po/mod/communicator.py", line 188, in synchronize
    raise PODocsError(e)
mod.communicator.PODocsError: [Errno 2] No such file or directory: '/Volumes/svnnew/agesage_/main/locale/nma/ja/temp/c3po_local_trans.csv'
```

And folder /Volumes/svnnew/agesage_/main/locale/nma was deleted.

**Comment by stefan8** [comment]
Probably this was issued before. Does it occur with latest version?
